import puppeteer from 'puppeteer-core'
const b = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox', '--disable-gpu'] })
const p = await b.newPage()
await p.goto('http://127.0.0.1:5173/login', { waitUntil: 'networkidle2', timeout: 30000 })
const inputs = await p.$$('input')
await inputs[0].type('admin'); await inputs[1].type('admin123')
await p.click('button'); await new Promise(r => setTimeout(r, 2500))
const got = await p.evaluate(() => document.querySelector('div[style*="fs-page"]')?.textContent?.trim() || '')
const title = await p.title()
console.log(`dashboard.welcome(en): ${got}`)
console.log(`document.title(en): ${title}`)
const ok = got === 'Welcome to Snail Quant' && title.includes('Snail Quant') && !title.includes('Trading')
console.log(ok ? '✓ 全绿' : '✗ 失败')
await b.close()
process.exit(ok ? 0 : 1)
