import puppeteer from 'puppeteer-core'
const BASE = 'http://localhost:5173'
const b = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox', '--disable-gpu'] })
const p = await b.newPage()
await p.evaluateOnNewDocument(() => {
  Object.defineProperty(navigator, 'language', { get: () => 'zh-CN', configurable: true })
  Object.defineProperty(navigator, 'languages', { get: () => ['zh-CN', 'en'], configurable: true })
})
await p.setViewport({ width: 1600, height: 900 })
await p.goto(`${BASE}/login`, { waitUntil: 'networkidle2', timeout: 30000 })
await p.evaluate(() => localStorage.removeItem('lang'))
await p.type('input', 'admin')
const inputs = await p.$$('input')
await inputs[1].type('admin123')
await p.click('.el-button--primary')
await p.waitForNavigation({ waitUntil: 'networkidle2', timeout: 15000 }).catch(() => {})
await new Promise(r => setTimeout(r, 1200))
await p.goto(`${BASE}/observe`, { waitUntil: 'networkidle2', timeout: 30000 })
await new Promise(r => setTimeout(r, 1500))
console.log('[a-zh observe 页签]', await p.evaluate(() => [...document.querySelectorAll('.el-tabs__item, [role=tab]')].map(e => e.textContent.trim()).join(' | ')))
await p.goto(`${BASE}/logs`, { waitUntil: 'networkidle2', timeout: 30000 })
await new Promise(r => setTimeout(r, 1500))
console.log('[b-zh logs title]', await p.evaluate(() => [...document.querySelectorAll('[title]')].map(e => e.getAttribute('title')).filter(t => t.includes('筛选')).join(' | ')))
await p.goto(`${BASE}/perm-resources?tab=nav`, { waitUntil: 'networkidle2', timeout: 30000 })
await new Promise(r => setTimeout(r, 1800))
console.log('[c-zh perm nav 行]', await p.evaluate(() => [...document.querySelectorAll('.el-table__body tr')].slice(7, 13).map(tr => [...tr.querySelectorAll('td .cell')].map(td => td.textContent.trim()).slice(0, 2).join('/')).join(' | ')))
// d. 弹窗(zh:编辑钮)
await p.goto(`${BASE}/settings?tab=run`, { waitUntil: 'networkidle2', timeout: 30000 })
await new Promise(r => setTimeout(r, 1800))
await p.evaluate(() => { [...document.querySelectorAll('[title]')].find(e => (e.getAttribute('title')||'').includes('编辑'))?.closest('button')?.click() })
await new Promise(r => setTimeout(r, 900))
console.log('[d-弹窗 margin]', await p.evaluate(() => {
  const fi = document.querySelector('.el-dialog .el-form-item')
  return fi ? getComputedStyle(fi).marginBottom : 'NO-DLG'
}))
await b.close()
